POST http://localhost:3003/clientes
Content-Type: application/json

{
    "nome": "Saullo",
    "cpf": 88888888888,
    "dataNascimento": "08/08/2002"
}

###

GET http://localhost:3003/clientes