// ENDEREÇO PADRÃO
GET http://localhost:3003/users

###
// FILTRO POR NOME
GET http://localhost:3003/users?name=Aline

###
//FILTRO POR TIPO
GET http://localhost:3003/users/CX

###
// ORDENAÇÃO
GET http://localhost:3003/users/order?sort=name&order=ASC

###
// PAGINAÇÃO
GET http://localhost:3003/users/page?size=5&page=1