POST http://localhost:3003/user/signup 
Content-Type: application/json 

{
	"name": "Saullo",
	"email": "saullo@lbn.com",
	"password": "123456"
}

###
POST http://localhost:3003/user/login 
Content-Type: application/json 

{
	"email": "bob@lbn.com",
	"password": "123456"
}

###
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZhNmJlMDNiLTA5ZWYtNGUyOC04NDY1LTI4Njk5Y2ViOTU1NyIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NjEzNzI2NjEsImV4cCI6MTY2MTM3NjI2MX0.ywbQM7r9HYbul5d8flM4pu1E7u9GhOGEXH8upYmAxNU

###
GET http://localhost:3003/user/1cf3f207-158c-4eac-8e08-663aa3639810
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZhNmJlMDNiLTA5ZWYtNGUyOC04NDY1LTI4Njk5Y2ViOTU1NyIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NjEzNzI2NjEsImV4cCI6MTY2MTM3NjI2MX0.ywbQM7r9HYbul5d8flM4pu1E7u9GhOGEXH8upYmAxNU

###
POST http://localhost:3003/recipe/create 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFjZjNmMjA3LTE1OGMtNGVhYy04ZTA4LTY2M2FhMzYzOTgxMCIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NjE2Mzk4OTUsImV4cCI6MTY2MTY0MzQ5NX0.yVNl0zPMNKRUmi7Y2gKeD_LEgQ6Xf1Cj-i5ONEsLFdY

{
	"title": "Macarrão de abobrinha simples",
	"description": "Traga leveza e um sabor diferente ao tradicional preparo do macarrão trocando a massa por abobrinha. Basta fatiar o vegetal em tiras fininhas, com uma faca ou uma mandolina. Assim, os fios ficam parecendo macarrão e com excelente sabor."
}


###
GET http://localhost:3003/recipe/a05ffbdb-0265-4bac-84b6-ea9cdef13fd2 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZhNmJlMDNiLTA5ZWYtNGUyOC04NDY1LTI4Njk5Y2ViOTU1NyIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NjE0NzE1NTcsImV4cCI6MTY2MTQ3NTE1N30.8KVX8YhnHA0vHNFbXJj8l1eb992nRtkCJ00Q5tCbfmE

###
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFjZjNmMjA3LTE1OGMtNGVhYy04ZTA4LTY2M2FhMzYzOTgxMCIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NjE2NDA4NTMsImV4cCI6MTY2MTY0NDQ1M30.2jLKoXXOWhc1fjqs2QE-HsaNRRWPxx00H5e73mhv6aQ

{
	"userToFollowId": "fa6be03b-09ef-4e28-8465-28699ceb9557"
}

###
POST http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZhNmJlMDNiLTA5ZWYtNGUyOC04NDY1LTI4Njk5Y2ViOTU1NyIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NjE2MzQ3NTcsImV4cCI6MTY2MTYzODM1N30.OrPmQzYmKT8-WhviRBY3JJ0ToOolv4KgHrSzailn6SA

{
	"userToUnfollowId": "1cf3f207-158c-4eac-8e08-663aa3639810"
}