POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "Thamyres",
    "email": "thamyres@email.com",
    "password": "123456"
}

###
POST http://localhost:3003/post/create 
Content-Type: application/json 

{
    "photo": "https://picsum.photos/200/150",
    "description": "Photo 00",
    "type": "normal",
    "authorId": "8077d7e2-f26b-4ed6-b2ef-e7f028649dde"
}

###
GET http://localhost:3003/post/9ba15479-6b0e-4df0-93ea-58c10775c5eb

###
POST http://localhost:3003/user/65c046ad-d9d8-4f2c-90df-fd5ab746ca43
Content-Type: application/json

{
    "friendId": "f68abb3a-a386-48e0-a4ec-17a858beafe4"
}