POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "Thamyres",
    "email": "thamyres@email.com",
    "password": "123456"
}

###
POST http://localhost:3003/post/create 
Content-Type: application/json 

{
    "photo": "https://picsum.photos/200/150",
    "description": "Photo 00",
    "type": "normal",
    "authorId": "8077d7e2-f26b-4ed6-b2ef-e7f028649dde"
}

###
GET http://localhost:3003/post/b399f532-c73d-4cb4-a3b7-7e82e3be7beb

###
POST http://localhost:3003/user/65c046ad-d9d8-4f2c-90df-fd5ab746ca43
Content-Type: application/json

{
    "friendId": "f68abb3a-a386-48e0-a4ec-17a858beafe4"
}

###
DELETE  http://localhost:3003/user/friendship
Content-Type: application/json

{
    "userId": "34396b65-44f4-47e6-b04f-45c2ee5c7e2a",
    "friendId": "8077d7e2-f26b-4ed6-b2ef-e7f028649dde"
}

###
GET http://localhost:3003/post/user/65c046ad-d9d8-4f2c-90df-fd5ab746ca43